services:
  e2e-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile.e2e
    working_dir: /app
    environment:
      VITE_EMULATOR_RTD_HOST: rtdb-emulator
      VITE_EMULATOR_AUTH_HOST: rtdb-emulator
      HEADLESS: '1'
      APP_URL: http://web:5173/
    depends_on:
      rtdb-emulator:
        condition: service_healthy
      web:
        condition: service_healthy
      stun:
        condition: service_started
    profiles: ['e2e']

  web:
    environment:
      MODE: e2e
